@echo off
set OUT=%~dp0..\db_raw.txt
sqlcmd -S 172.20.229.2 -d BMSSafariRwp -U admin -P Pakistan@786 -C -u -Q "SET NOCOUNT ON; SELECT c.TABLE_SCHEMA, c.TABLE_NAME, c.COLUMN_NAME, c.DATA_TYPE, c.CHARACTER_MAXIMUM_LENGTH, c.NUMERIC_PRECISION, c.NUMERIC_SCALE, c.IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS c INNER JOIN INFORMATION_SCHEMA.TABLES t ON c.TABLE_SCHEMA = t.TABLE_SCHEMA AND c.TABLE_NAME = t.TABLE_NAME WHERE t.TABLE_TYPE = N'BASE TABLE' AND t.TABLE_SCHEMA NOT IN (N'INFORMATION_SCHEMA', N'sys') ORDER BY c.TABLE_SCHEMA, c.TABLE_NAME, c.ORDINAL_POSITION" -W -s"|" -h-1 -o "%OUT%"
exit /b %ERRORLEVEL%
